accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

# app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    # path('change_password/', views.changepasssword, name='change_password'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_complete.html'),
         name='password_reset_complete'),

    # change password
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='change_password.html'),
         name='password_change'),
    path('change_password_done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
         name='password_change_done'),
]

collab_suite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('suiteapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

suiteapp/urls.py
# from dajaxice.core import dajaxice_autodiscover, dajaxice_config
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.conf import settings

from django.urls import path
from. import views

app_name = 'suiteapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('mysite/', views.mysite, name='mysite'),
    path('task/', views.task, name='task'),
    path('repository/', views.repository, name='repository'),
    # path('taskpage/', views.taskpage, name='taskpage'),
    path('taskpage/??/', views.taskpageFunc, name='taskpage'),
    # path('add_site_member/<str:pk>/', views.add_site_member, name='add_site_member'),
    path('add_site_member/teenage-pregnancy/', views.AjaxHandlerView.as_view(), name='add_site_member'),
    path('delete_files/<str:dept>/<str:pk>/', views.deleteFile, name='deletefile'),
    # delete_files/<str:dept>/??/+=/<str:pk>/t4/????piAss??/
    path('delete_folder/<str:pk>/??/+=/<str:dep>/t4/????piAss??<str:name>ug/<str:fk>/', views.deleteFolder, name='delete_folder'),
    path('read/<str:pk>/', views.openfile, name='open_file'),
    path('open_department/<str:pk>/', views.openDepartment, name='open_department'),
    path('open_faculty/<str:pk>/', views.openFaculty, name='open_faculty'),
    path('open_folder/<str:pk>/', views.open_folder, name='open_folder')
]

suiteapp/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


# Create your models here.
class Faculty(models.Model):
    faculty_id = models.AutoField(primary_key=True)
    faculty_name = models.CharField(
        max_length=255,
        unique=True,
        blank=True,
        default='_'
    )

    def __str__(self):
        return str(self.faculty_name)

    class Meta:
        verbose_name_plural = 'Faculties'


class Department(models.Model):
    dept_id = models.AutoField(primary_key=True)
    dept_name = models.CharField(
        max_length=255,
        unique=True,
        blank=True, default='-'
    )
    faculty = models.ForeignKey(Faculty, null=True, verbose_name="faculty", on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.dept_name)


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            username=username,
        )

        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    username = models.CharField(
        verbose_name='username',
        max_length=255,
        unique=True,
    )
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    firstname = models.CharField(
        verbose_name='firstname',
        max_length=255,
        null=True,
    )
    surname = models.CharField(
        verbose_name='lastname',
        max_length=255,
        null=True,
    )
    othername = models.CharField(
        verbose_name='middlename',
        max_length=255,
        null=True,
    )
    gender = models.CharField(
        verbose_name='gender',
        max_length=255,
        null=True, default='null',
    )
    # faculty = models.ForeignKey(
    #     Faculty,
    #     verbose_name='faculty',
    #     null=True, default='null',
    #     on_delete=models.SET_NULL,
    # )
    department = models.ForeignKey(
        Department,
        verbose_name='department',
        null=True,
        on_delete=models.SET_NULL,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username


    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    def get_full_name(self):
        # The user is identified by their email address
        return self.firstname + " " + self.othername + " " + self.surname

    class Meta:
        verbose_name_plural = 'Users'


class Folder(models.Model):
    folder_id = models.AutoField(primary_key=True)
    folder_name = models.CharField(max_length=255)
    created_on = models.DateTimeField(auto_now_add=True)
    is_rep = models.BooleanField(default=True)
    department = models.ForeignKey(Department, blank=True, null=True, on_delete=models.SET_NULL)
    faculty = models.ForeignKey(Faculty, blank=True, null=True, on_delete=models.SET_NULL)
    created_by = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    main_folder = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.folder_name)

    
class File(models.Model):
    uploaded_by = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    file_id = models.AutoField(primary_key=True)
    filepath = models.FileField(upload_to='files/', null=True, verbose_name="")
    uploaded_at = models.DateTimeField(auto_now_add=True)
    department = models.ForeignKey(Department, blank=True, null=True, on_delete=models.SET_NULL,)
    faculty = models.ForeignKey(Faculty, blank=True, null=True, on_delete=models.SET_NULL, )
    is_rep = models.BooleanField(default=False)
    folder = models.ForeignKey(Folder, blank=True, null=True, on_delete=models.CASCADE)
    is_task = models.BooleanField(default=False)

    def __str__(self):
        return str(self.filepath)  # + ":" + str(self.filepath)

    def last_10_files(self):
        return File.objects.order_by('-file_id').all()

    def display_text_file(self):
        with open(self.filepath.path) as fp:
            return fp.read().replace('\n', '<br>')


class Site(models.Model):
    site_name = models.CharField(max_length=200)
    site_id = models.CharField(max_length=200, primary_key=True, unique=True)
    description = models.TextField()
    site_visibilty = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.site_name)


class Task(models.Model):
    task_id = models.AutoField(primary_key=True)
    priority = models.CharField(max_length=7, )
    due_date = models.DateField(null=True)
    due_time = models.TimeField(null=True)
    assignee = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    comment = models.TextField(blank=True)
    # assigner = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    # task_file = models.FileField(upload_to='files/', null=True, verbose_name="",)

    def __str__(self):
        return str(self.comment)


class Taskfile(models.Model):
    task_id = models.AutoField(primary_key=True)
    task_file = models.FileField(upload_to='files/', null=True, verbose_name="")


class Site_Folder(models.Model):
    folder_id = models.AutoField(primary_key=True)
    folder_name = models.CharField(max_length=255, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.folder_name)


class Role(models.Model):
    role = models.CharField(max_length=20)
    
    def __str__(self):
        return str(self.id)


class SiteUser(models.Model):
    site = models.ForeignKey(Site, null=True, on_delete=models.SET_NULL) 
    user = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    role = models.ForeignKey(Role, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.site)

suiteapp/forms.py
from django import forms
from .models import *


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    GEN_CHOICES = [('select', ''),
                   ('male', 'Male'),
                   ('female', 'Female'),
                   ('other', 'Other')]
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                    'placeholder': 'enter password'}))
    password2 = forms.CharField(label='Password confirmation',
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 're-enter password'}))
    # department = forms.ModelChoiceField(queryset=Department.objects.all(),
    #                                     widget=forms.Select(attrs={'class': 'form-control'}))
    # faculty = forms.ModelChoiceField(queryset=Faculty.objects.all(),
    #                                  widget=forms.Select(attrs={'class': 'form-control'}))
    gender = forms.ChoiceField(choices=GEN_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'email'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'username'}))
    othername = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                              'placeholder': 'othernames'}))
    surname = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter your surname'}))
    firstname = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter firstname'}))

    # faculty = forms.SelectMultiple(attrs={'required': "required"})

    class Meta:
        model = MyUser
        fields = ('firstname', 'email', 'username', 'department', 'password1',
                  'password2', 'gender', 'surname', 'othername')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ["filepath", "uploaded_by", 'department', 'faculty', 'is_rep', 'folder', 'is_task']


CHOICES = [('private', 'Private'),
           ('medium', 'Medium'),
           ('public', 'Public')]


class SiteForm(forms.ModelForm):
    site_visibility = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(attrs={'class': 'form-ckeck'}))
    site_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter the name of the site...', 'class': 'form-control'}))
    site_id = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'site id...', 'class': 'form-control'}))

    # description = forms.CharField(widget=forms.TextInput(attrs={'':'form-control'}))

    class Meta:
        model = Site
        fields = ["site_name", "site_id", "description", 'site_visibility']


class FolderForm(forms.ModelForm):
    folder_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter the folder name...'}))

    class Meta:
        model = Folder
        fields = ['folder_name', 'is_rep', 'faculty', 'department', 'created_by', 'main_folder']


class SiteUserForm(forms.ModelForm):
    class Meta:
        model = SiteUser
        fields = ['site', 'user', 'role']


class DateInput(forms.DateInput):
    input_type = 'date'

    def clean_date(self):
        cleaned_data = self.cleaned_data
        due_date = cleaned_data.get("due_date")
        return due_date


class TimeInput(forms.TimeInput):
    input_type = 'time'

    def clean_time(self):
        cleaned_data = self.cleaned_data
        due_time = cleaned_data.get("due_time")
        return due_time


class TimeForm(forms.Form):
    time_field = forms.TimeField(widget=TimeInput())


class TaskForm(forms.ModelForm):
    PRIO_CHOICES = [('high', 'Hgh'),
                    ('medium', 'Medium'),
                    ('low', 'Low')]
    # task_file =  forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    priority = forms.ChoiceField(choices=PRIO_CHOICES, widget=forms.Select(attrs={'class': 'form-control col-sm-2'}))
    due_date = forms.DateField(widget=DateInput(attrs={'class': 'form-control col-sm-2'}))
    due_time = forms.TimeField(widget=TimeInput(attrs={'class': 'form-control col-sm-2'}))
    comment = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control col-sm-4', 'rows': 7, }))

    class Meta:
        model = Task
        fields = ['priority', 'due_date', 'due_time', 'assignee', 'comment', ]


class TaskFileForm(forms.ModelForm):
    filepath = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True, 'class': 'form-control col-sm-4'}))

    class Meta:
        model = File
        fields = ['is_task', 'filepath', 'uploaded_by']
# select for dropdown
# choice for radio button

suiteapp/templates/page/delete.html
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">

<meta name="robots" content="NONE,NOARCHIVE">

<div class="breadcrumbs">
	<a href="">Delete File</a>
	&rsaquo;Files deleted can't be restored
</div>

<p>Are you sure you want to delete "{{ file.filepath }} {{ folder.folder_name }}" ?</p>

{% if file.department == user.department or folder.department == user.department %}
	<a href="{% url 'suiteapp:open_department' user.department.dept_id %}">Cancel</a>
{% elif file.faculty == user.department.faculty or folder.faculty == user.department.faculty %}
	<a href="{% url 'suiteapp:open_faculty' user.department.faculty.faculty_id %}">Cancel</a>
{% elif file.is_rep is True or folder.is_rep is True %}
	<a href="{% url 'suiteapp:repository' %}">Cancel</a>
{% elif file.folder is not None %}
<a href="{% url 'suiteapp:open_folder' file.folder.folder_id %}">Cancel</a>
{% elif folder.main_folder is not None %}
	<a href="{% url 'suite	app:open_folder' folder.main_folder.folder_id %}">Cancel</a>
{% elif file.department is blank and file.faculty is blank and file.folder is blank %}
	<a href="{% url 'suiteapp:mysite' %}">Cancel</a>
{% elif folder.department is blank and folder.faculty is blank and folder.main_folder is blank %}
	<a href="{% url 'suiteapp:mysite' %}">Cancel</a>
{% endif %}
<form method="POST" action="">
	{% csrf_token %}
	<input type="submit" name="Confirm" value="Confirm">
</form>

suiteapp/templates/page/details.html
{% extends 'base.html' %}
{% block details %}
{% endblock %}

suiteapp/templates/page/doc_page.html
<!DOCTYPE html>
<html>
    <body>
        <div class="container" style="margin-left:10%;">
            <div class="row">
                <!-- <button><i class=""></i></button> -->
            </div>
            <div class="row">
                {{file.filepath.url}}"
                <iframe src="https://docs.google.com/gview?url={{ file.filepath.url }}&embedded=true" width="100%" height="500px" scrolling='no' frameborder='1'>

                </iframe>
            </div>
        </div>
</body>
</html>

suiteapp/templates/page/open.html
{% extends 'base.html' %}
{% block open %}
{% load static %}
{% url 'suiteapp:open_department' user.department.dept_id as open_department %}
{% url 'suiteapp:open_faculty' user.department.faculty.faculty_id as open_faculty %}
{% url 'suiteapp:mysite' as mysite %}
{% url 'suiteapp:open_folder' folder.folder_id as open_folder %}

{% for message in messages %}
    <p style="color:red;"><b>{{ message }}</b></p>
{% endfor %}

<!-- uploadmodal -->
{% include 'controls/uploadmodal.html' %}

<!-- Createfoldermodal -->
{% include 'controls/createfoldermodal.html' %}

<!--body tab-->
<div class="container" style="margin-left: 15%">
    <br />
    <br />
    <br />
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" id="" role="tablist" >
      <li class="nav-item">
          <a class="nav-link fas fa-folder" data-toggle="modal" data-target="#folderModal" href="#" onclick="folderForm();"><r>Create folder</r></a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><r>Upload file</r></a>
          <div class="dropdown-menu">
                <a class="dropdown-item fas fa-folder" data-toggle="modal" data-target="#myModal" href="#" onclick="fileForm();"><r>Directory</r></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item fas fa-file-text blue" href="https://docs.google.com/document/u/0/"><r>google docs</r></a>
                <a class="dropdown-item fas fa-file-excel-o blue" href="https://docs.google.com/spreadsheets/u/0/"><r>google spreadsheet</r></a>
                <a class="dropdown-item fas fa-file-powerpoint-o blue" href="#"><r>google presentation</r></a>
          </div>
      </li>
    </ul>
</div>

    <!-- Side navbar -->
<div class="sidenav" style="margin-top:10%;">
    <h4 style="font-size:18px"></h4>
    <div class="card" style="width:80%; border:0px;">
        <div class="card-body" style="padding-top:0%;">
           <a href="">Add members</a>
           <a href="">Site members</a>
           <a href="">Chats</a>
        </div>
    </div>
</div>


<div class="main col-sm-9">
    <div class="container">
<!-- list of files  on department-->
        {% if request.path == open_department %}
            {% for folder in folders %}
                <div class="row border" style="width:100%; height:150px;">
                    <a href="{% url 'suiteapp:open_folder' folder.folder_id %}" class="row col-9">
                        <div class="col-sm-2" style="padding-top:5%; height:100%;">
                            <img src="{% static 'images/folder.jpeg' %}" width="50px" height="50px" style="padding-top:4%;" alt="">
                        </div>
                        <div class="col-sm-6">
                            <h5 style="padding-top:10%; margin-left:0px; width:100%;">{{ folder.folder_name }}</h5>
                        </div>
                    </a>
                    <div class="col-3" style="padding-top:5%;">
                        <ul type="none" style="font-size:12px;">
                            <li><a href="{% url 'suiteapp:delete_folder' folder.folder_id user.department.dept_id folder.folder_name folder.main_folder %}">Delete</a></li>
                            <li><a href="">Permissions</a></li>
                        </ul>
                    </div>
                </div>
                <br >
            {% endfor %}

            {% for file in files %}
                <div class="row border" id="files" style="border:1px groove gray; width:100%; height:150px;">
                    <div class="row col-9">
                        <span class="image col-sm-2" id="id_doc" style="padding-top:20px;">
                            <a href="{{ file.filepath.url }}"><img class="img_doc" src="{% static ''%}" width="70px" height="70px" alt="icon"></a>
                        </span>
                        <span class="filename col-sm-6" id="file_name" style="padding-top:8%;">
                            <h6 style="padding-left:0;"><a href="{% url 'suiteapp:open_file' file.file_id %}" id="filename"> {{ file.filepath|cut:"files/" }}</a></h6>
                        </span>
                    </div>
                    <span class="col-3" style="padding-top:5%;">
                        <ul type="none" style="font-size:12px;">
                            <li><a href="{% url 'suiteapp:deletefile' user.department.dept_id file.file_id %}">Delete</a></li>
                            <li><a href="">Permissions</a></li>
                            <li><a id="downloadfile" href="{{ file.filepath.url }}" download="{{ file.filepath.url }}">Download</a></li>
                        </ul>
                    </span>
                </div>
                <br />               
            {% endfor %}

    <!-- Faculty -->
        <!-- list of folders on faculty -->
        {% elif request.path == open_faculty %}
            {% for folder in folders %}
                <div class="row border" style="width:100%; height:150px;">
                    <a href="{% url 'suiteapp:open_folder' folder.folder_id %}" class="row col-9">
                        <div class="col-sm-2" style="padding-top:5%; height:100%;">
                            <img src="{% static 'images/folder.jpeg' %}" width="50px" height="50px" style="padding-top:4%;" alt="">
                        </div>
                        <div class="col-sm-6">
                            <h5 style="padding-top:10%; margin-left:0px; width:100%;">{{ folder.folder_name }}</h5>
                        </div>
                    </a>
                    <div class="col-3" style="padding-top:5%;">
                        <ul type="none" style="font-size:12px;">
                            <li><a href="{% url 'suiteapp:delete_folder' folder.folder_id user.department.faculty.faculty_id folder.folder_name folder.main_folder %}">Delete</a></li>
                            <li><a href="">Permissions</a></li>
                        </ul>
                    </div>
                </div>
                <br >
            {% endfor %}

            <!-- faculty files-->
            {% for file in files %}
                <div class="row border" id="files" style="border:1px groove gray; width:100%; height:150px;">
                    <div class="row col-9">
                        <span class="image col-sm-2" id="id_doc" style="padding-top:20px;">
                            <a href="{{ file.filepath.url }}"><img class="img_doc" src="{% static ''%}" width="70px" height="70px" alt="icon"></a>
                        </span>
                        <span class="filename col-sm-6" id="file_name" style="padding-top:8%;">
                            <h6 style="padding-left:0;"><a href="{% url 'suiteapp:open_file' file.file_id %}" id="filename"> {{ file.filepath|cut:"files/" }}</a></h6>
                        </span>
                    </div>
                    <span class="col-3" style="padding-top:5%;">
                        <ul type="none" style="font-size:12px;">
                            <li><a href="{% url 'suiteapp:deletefile' user.department.faculty.faculty_id file.file_id %}">Delete</a></li>
                            <li><a href="">Permissions</a></li>
                            <li><a id="downloadfile" href="{{ file.filepath.url }}" download="{{ file.filepath.url }}">Download</a></li>
                        </ul>
                    </span>
                </div>
                <br />
            {% endfor %}

    <!-- Mysite -->
        <!-- Mysite files -->
        {% elif request.path == mysite %}
            {% for file in files %}
                {% if file.uploaded_by == user and file.department == None and file.faculty == None %}
                <div class="row border" id="files" style="border:1px groove gray; width:100%; height:150px;">
                    <div class="row col-9">
                        <span class="image col-sm-2" id="id_doc" style="padding-top:20px;">
                            <a href="{{ file.filepath.url }}"><img class="img_doc" src="{% static ''%}" width="70px" height="70px" alt="icon"></a>
                        </span>

                        <span class="filename col-sm-6" id="file_name" style="padding-top:8%;">
                            <h6 style="padding-left:0;"><a href="{% url 'suiteapp:open_file' file.file_id %}" id="filename"> {{ file.filepath|cut:"files/" }}</a></h6>
                        </span>
                    </div>
                    <span class="col-3" style="padding-top:5%;">
                        <ul type="none" style="font-size:12px;">
                            <li><a href="{% url 'suiteapp:deletefile' file.uploaded_by file.file_id %}">Delete</a></li>
                            <li><a href="">Permissions</a></li>
                            <li><a id="downloadfile" href="{{ file.filepath.url }}" download="{{ file.filepath.url }}">Download</a></li>
                        </ul>
                    </span>
                </div>
                <br />   
                {% endif %}  
            {% endfor %}

            <!-- folders in mysite -->
            {% for folder in folders %}
            {% if folder.created_by == user and folder.department == None and folder.faculty == None and main_folder == None %}
                <div class="row border" style="width:100%; height:150px;">
                    <a href="{% url 'suiteapp:open_folder' folder.folder_id %}" class="row col-9">
                        <div class="col-sm-2 col-md-2" style="padding-top:5%; height:100%;">
                            <img src="{% static 'images/folder.jpeg' %}" width="50px" height="50px" style="padding-top:4%;" alt="">
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <h5 style="padding-top:10%; margin-left:0px; width:100%;">{{ folder.folder_name }}</h5>
                        </div>
                    </a>
                    <div class="col-3" style="padding-top:5%;">
                        <ul type="none" style="font-size:12px;">
                            <li><a href="{% url 'suiteapp:delete_folder' folder.folder_id user.department.faculty.faculty_id folder.folder_name folder.main_folder %}">Delete</a></li>
                            <li><a href="">Permissions</a></li>
                        </ul>
                    </div>
                </div>
                <br >
                {% endif %}
            {% endfor %}

<!--        {% elif request.path == open_folder %}-->
<!--        -->
<!--            {% for file in files %}-->
<!--                <div class="row border" id="files" style="border:1px groove gray; width:100%; height:150px;">-->
<!--                    <div class="row col-9">-->
<!--                        <span class="image col-sm-2" id="id_doc" style="padding-top:20px;">-->
<!--                            <a href="{{ file.filepath.url }}"><img class="img_doc" src="{% static ''%}" width="70px" height="70px" alt="icon"></a>-->
<!--                        </span>-->
<!--                        <span class="filename col-sm-6" id="file_name" style="padding-top:8%;">-->
<!--                            <h6 style="padding-left:0;"><a href="{% url 'suiteapp:open_file' file.file_id %}" id="filename"> {{ file.filepath|cut:"files/" }}</a></h6>-->
<!--                        </span>-->
<!--                    </div>-->
<!--                    <span class="col-3" style="padding-top:5%;">-->
<!--                        <ul type="none" style="font-size:12px;">-->
<!--                            <li><a href="{% url 'suiteapp:deletefile' file.uploaded_by file.file_id %}">Delete</a></li>-->
<!--                            <li><a href="">Permissions</a></li>-->
<!--                            <li><a id="downloadfile" href="{{ file.filepath.url }}" download="{{ file.filepath.url }}">Download</a></li>-->
<!--                        </ul>-->
<!--                    </span>-->
<!--                </div>-->
<!--                <br />               -->
<!--            {% endfor %}-->
           

        {% endif %}

    </div>
</div>
<script>fileForm()</script>
<!-- <h1 id="path">{{ request.path }}</h1> -->
<!-- <script type="text/javascript" src="{% static 'js/openscript.js' %}"></script> -->
{% endblock %}

suiteapp/templates/page/search.html
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>
  {% for user in filter.qs %}
    <li>{{ user.get_full_name }}</li>
  {% endfor %}
  </ul>