accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

# app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    # path('change_password/', views.changepasssword, name='change_password'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_complete.html'),
         name='password_reset_complete'),

    # change password
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='change_password.html'),
         name='password_change'),
    path('change_password_done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
         name='password_change_done'),
]

collab_suite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('suiteapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

suiteapp/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


# Create your models here.
class Faculty(models.Model):
    faculty_id = models.AutoField(primary_key=True)
    faculty_name = models.CharField(
        max_length=255,
        unique=True,
        blank=True,
        default='_'
    )

    def __str__(self):
        return str(self.faculty_name)

    class Meta:
        verbose_name_plural = 'Faculties'


class Department(models.Model):
    dept_id = models.AutoField(primary_key=True)
    dept_name = models.CharField(
        max_length=255,
        unique=True,
        blank=True, default='-'
    )
    faculty = models.ForeignKey(Faculty, null=True, verbose_name="faculty", on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.dept_name)


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            username=username,
        )

        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    username = models.CharField(
        verbose_name='username',
        max_length=255,
        unique=True,
    )
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    firstname = models.CharField(
        verbose_name='firstname',
        max_length=255,
        null=True,
    )
    surname = models.CharField(
        verbose_name='lastname',
        max_length=255,
        null=True,
    )
    othername = models.CharField(
        verbose_name='middlename',
        max_length=255,
        null=True,
    )
    gender = models.CharField(
        verbose_name='gender',
        max_length=255,
        null=True, default='null',
    )
    # faculty = models.ForeignKey(
    #     Faculty,
    #     verbose_name='faculty',
    #     null=True, default='null',
    #     on_delete=models.SET_NULL,
    # )
    department = models.ForeignKey(
        Department,
        verbose_name='department',
        null=True,
        on_delete=models.SET_NULL,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username


    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    def get_full_name(self):
        # The user is identified by their email address
        return self.firstname + " " + self.othername + " " + self.surname

    class Meta:
        verbose_name_plural = 'Users'


class Folder(models.Model):
    folder_id = models.AutoField(primary_key=True)
    folder_name = models.CharField(max_length=255)
    created_on = models.DateTimeField(auto_now_add=True)
    is_rep = models.BooleanField(default=True)
    department = models.ForeignKey(Department, blank=True, null=True, on_delete=models.SET_NULL)
    faculty = models.ForeignKey(Faculty, blank=True, null=True, on_delete=models.SET_NULL)
    created_by = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    main_folder = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.folder_name)

    
class File(models.Model):
    uploaded_by = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    file_id = models.AutoField(primary_key=True)
    filepath = models.FileField(upload_to='files/', null=True, verbose_name="")
    uploaded_at = models.DateTimeField(auto_now_add=True)
    department = models.ForeignKey(Department, blank=True, null=True, on_delete=models.SET_NULL,)
    faculty = models.ForeignKey(Faculty, blank=True, null=True, on_delete=models.SET_NULL, )
    is_rep = models.BooleanField(default=False)
    folder = models.ForeignKey(Folder, blank=True, null=True, on_delete=models.CASCADE)
    is_task = models.BooleanField(default=False)

    def __str__(self):
        return str(self.filepath)  # + ":" + str(self.filepath)

    def last_10_files(self):
        return File.objects.order_by('-file_id').all()

    def display_text_file(self):
        with open(self.filepath.path) as fp:
            return fp.read().replace('\n', '<br>')


class Site(models.Model):
    site_name = models.CharField(max_length=200)
    site_id = models.CharField(max_length=200, primary_key=True, unique=True)
    description = models.TextField()
    site_visibilty = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.site_name)


class Task(models.Model):
    task_id = models.AutoField(primary_key=True)
    priority = models.CharField(max_length=7, )
    due_date = models.DateField(null=True)
    due_time = models.TimeField(null=True)
    assignee = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    comment = models.TextField(blank=True)
    # assigner = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    # task_file = models.FileField(upload_to='files/', null=True, verbose_name="",)

    def __str__(self):
        return str(self.comment)


class Taskfile(models.Model):
    task_id = models.AutoField(primary_key=True)
    task_file = models.FileField(upload_to='files/', null=True, verbose_name="")


class Site_Folder(models.Model):
    folder_id = models.AutoField(primary_key=True)
    folder_name = models.CharField(max_length=255, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.folder_name)


class Role(models.Model):
    role = models.CharField(max_length=20)
    
    def __str__(self):
        return str(self.id)


class SiteUser(models.Model):
    site = models.ForeignKey(Site, null=True, on_delete=models.SET_NULL) 
    user = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    role = models.ForeignKey(Role, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.site)

suiteapp/forms.py
from django import forms
from .models import *


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    GEN_CHOICES = [('select', ''),
                   ('male', 'Male'),
                   ('female', 'Female'),
                   ('other', 'Other')]
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                    'placeholder': 'enter password'}))
    password2 = forms.CharField(label='Password confirmation',
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 're-enter password'}))
    # department = forms.ModelChoiceField(queryset=Department.objects.all(),
    #                                     widget=forms.Select(attrs={'class': 'form-control'}))
    # faculty = forms.ModelChoiceField(queryset=Faculty.objects.all(),
    #                                  widget=forms.Select(attrs={'class': 'form-control'}))
    gender = forms.ChoiceField(choices=GEN_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'email'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'username'}))
    othername = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                              'placeholder': 'othernames'}))
    surname = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter your surname'}))
    firstname = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter firstname'}))

    # faculty = forms.SelectMultiple(attrs={'required': "required"})

    class Meta:
        model = MyUser
        fields = ('firstname', 'email', 'username', 'department', 'password1',
                  'password2', 'gender', 'surname', 'othername')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ["filepath", "uploaded_by", 'department', 'faculty', 'is_rep', 'folder', 'is_task']


CHOICES = [('private', 'Private'),
           ('medium', 'Medium'),
           ('public', 'Public')]


class SiteForm(forms.ModelForm):
    site_visibility = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(attrs={'class': 'form-ckeck'}))
    site_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter the name of the site...', 'class': 'form-control'}))
    site_id = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'site id...', 'class': 'form-control'}))

    # description = forms.CharField(widget=forms.TextInput(attrs={'':'form-control'}))

    class Meta:
        model = Site
        fields = ["site_name", "site_id", "description", 'site_visibility']


class FolderForm(forms.ModelForm):
    folder_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter the folder name...'}))

    class Meta:
        model = Folder
        fields = ['folder_name', 'is_rep', 'faculty', 'department', 'created_by', 'main_folder']


class SiteUserForm(forms.ModelForm):
    class Meta:
        model = SiteUser
        fields = ['site', 'user', 'role']


class DateInput(forms.DateInput):
    input_type = 'date'

    def clean_date(self):
        cleaned_data = self.cleaned_data
        due_date = cleaned_data.get("due_date")
        return due_date


class TimeInput(forms.TimeInput):
    input_type = 'time'

    def clean_time(self):
        cleaned_data = self.cleaned_data
        due_time = cleaned_data.get("due_time")
        return due_time


class TimeForm(forms.Form):
    time_field = forms.TimeField(widget=TimeInput())


class TaskForm(forms.ModelForm):
    PRIO_CHOICES = [('high', 'Hgh'),
                    ('medium', 'Medium'),
                    ('low', 'Low')]
    # task_file =  forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    priority = forms.ChoiceField(choices=PRIO_CHOICES, widget=forms.Select(attrs={'class': 'form-control col-sm-2'}))
    due_date = forms.DateField(widget=DateInput(attrs={'class': 'form-control col-sm-2'}))
    due_time = forms.TimeField(widget=TimeInput(attrs={'class': 'form-control col-sm-2'}))
    comment = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control col-sm-4', 'rows': 7, }))

    class Meta:
        model = Task
        fields = ['priority', 'due_date', 'due_time', 'assignee', 'comment', ]


class TaskFileForm(forms.ModelForm):
    filepath = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True, 'class': 'form-control col-sm-4'}))

    class Meta:
        model = File
        fields = ['is_task', 'filepath', 'uploaded_by']
# select for dropdown
# choice for radio button

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from suiteapp.forms import *
from suiteapp.models import *


# Create your views here.
def signin(request):
    if request.user.is_authenticated:
        return redirect('suiteapp:index')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('suiteapp:index')
            else:
                messages.error(request, 'Invalid Credentials or account not available !!!')
                return render(request, 'login.html')
        else:
            return render(request, 'login.html')


def signout(request):
    logout(request)
    return redirect('login')


@login_required(login_url='login')
def changepasssword(request):
    return render(request, 'change_password.html')


# def register(request):
#     if request.method == 'POST':
#         firstname = request.POST['username']
#         surname = request.POST['surname']
#         othername = request.POST['othername']
#         username = request.POST['username']
#         email = request.POST['email']
#         gender = request.POST['gender']
#         department = request.POST['department']
#         password1 = request.POST['password1']
#         password2 = request.POST['password2']
#
#         user = MyUser.objects.create_user(firstname=firstname, username=username, email=email, department=department,
#                                           password=password2, surname=surname, gender=gender,
#                                           othername=othername,
#                                           )
#         user.save()
#         return redirect('login')
#     else:
#         userform = UserCreationForm()
#         context = {'userform': userform}
#         return render(request, 'register.html', context)

def register(request):
    if request.method == 'POST':
        userform = UserCreationForm(request.POST)
        if userform.is_valid():
            userform.save()
            return redirect('login')
    else:
        userform = UserCreationForm()
        context = {'userform': userform}
        return render(request, 'register.html', context)

accounts/templates/change_password.html
{% extends 'password_base.html' %}
{% block change %}
<div id="content-main">
<form method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}
        Please correct the error below.
        {% else %}
        Please correct the errors below.
        {% endif %}
    </p>
{% endif %}


<p>Please enter your old password, for security’s sake, and then enter your new password twice so we can verify you typed it in correctly.</p>
</div>
<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.old_password.errors }}
    {{ form.old_password.label_tag }} {{ form.old_password }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    {{ form.new_password1.label_tag }} {{ form.new_password1 }}
    {% if form.new_password1.help_text %}
    <div class="help">{{ form.new_password1.help_text|safe }}</div>
    {% endif %}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    {{ form.new_password2.label_tag }} {{ form.new_password2 }}
    {% if form.new_password2.help_text %}
    <div class="help">{{ form.new_password2.help_text|safe }}</div>
    {% endif %}
</div>
<div class="submit-row">
    <input type="submit" value="Change my password" class="default">
</div>
</fieldset>
</form>
</div>
{% endblock %}


accounts/templates/login.html
<!DOCTYPE html>
{% url 'index' as index %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Page</title>

    <!-- Load an icon library to show a hamburger menu (bars) on small screens -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/responsiveness.css' %}" />


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

   
</head>
<body class="login-body">

    <div class="form" style="height: 100%;">
        <div class="container-fluid">
            <div class="">
                <h1 style="color: blanchedalmond;">Work Better, Together</h1>
                <p style="color: blanchedalmond; font: 18px;">The easiest way to get your work done.
                Share tasks, projects and files with anyone you work with.</p>
                {% for message in messages %}
                    <p style="color:red;"><b>{{ message }}</b></p>
                {% endfor %}
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="uname" class="card-head">Username :</label> <br />
                        <input type="text" class="form-control" name="username" id="uname" placeholder="username"> <br />
                        <label for="pword">Password</label> <br />
                        <input type="password" class="form-control" name="password" id="pword" placeholder="password"> <br />
                        <input type="submit" class="btn btn-light" value="Sign in">
                    </div>
                </form>
                <span>Forget password?</span><a href="{% url 'reset_password' %}" style="color:#4e33b7; text-decoration:underline;"> Reset Password</a>
<!--                 <br />or-->
<!--                <p>click<a href="{% url 'register' %}" style="color:white;">create an account</a></p>-->
            </div>
        </div>
    </div>
</body>
</html>

accounts/templates/password_change_done.html
{% extends 'password_base.html' %}
{% block change_done %}
<!--{% block title %}{{ title }}{% endblock %}-->
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
<p>Your password was changed.</p>
<p><a href="{% url 'siteapp:index' %}">Click</a> to return to Home</p>
{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends 'password_base.html' %}
{% block reset_confirm %}

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-password1">
        {{ form.new_password1.errors }}
        <label for="id_new_password1">New password:</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-row field-password2">
        {{ form.new_password2.errors }}
        <label for="id_new_password2">Confirm password:</label>
        {{ form.new_password2 }}
    </div>
    <input type="submit" value="Change my password">
</fieldset>
</form>

{% endblock %}

accounts/templates/password_reset_done.html
{% extends 'password_base.html' %}

{% block done %}

    <!-- Content -->
    <div id="content" class="colM">

        <h1>Password reset sent</h1>


<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

        <br class="clear">
    </div>
    <!-- END Content -->
{% endblock %}

accounts/templates/register.html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="container form-group border" style="margin-top:10px;">
    <h4 style="padding-top:5px;padding-bottom:5px;">Fill Form to create Account</h4>
    <form method="post" action="" class="col-md-12 border-top">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-sm-4">
              <label for="id_firstname">Firstname :</label>
              {{ userform.firstname }}
            </div>
            <div class="form-group col-sm-4">
              <label for="id_lastname">Surname :</label>
              {{ userform.surname}}
            </div>
            <div class="form-group col-sm-4">
              <label for="id_lastname">Other names :</label>
              {{ userform.othername }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-sm-4">
                  <label for="id_lastname">Username :</label>
                  {{ userform.username }}
            </div>
            <div class="form-group col-sm-5">
                <label for="id_email">Email :</label>
                {{ userform.email }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-sm-4">
              <label for="id_gender">Gender :</label>
              {{ userform.gender }}
            </div>
            <div class="form-group col-sm-4">
              <label for="id_department">Department :</label>
              {{ userform.department }}
            </div>
            <div class="form-group col-sm-6">
              <label for="id_faculty">Faculty :</label>

            </div>
        </div>
        <div class="form-group">
            <div class="form-group col-sm-6">
              <label for="id_password1">Password :</label>
              {{ userform.password1 }}
            </div>
            <div class="form-group col-sm-6">
              <label for="id_password2">Confrim password :</label>
              {{ userform.password2 }}
            </div>
        </div>
        <div class="form-footer">
            <button type="submit" class="btn btn-primary col-sm-4">Save</button>
            <a href="{% url 'login' %}" class="btn btn-danger col-sm-3">Cancel</a>
        </div>
    </form>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

accounts/templates/reset_complete.html
{% extends 'password_base.html' %}
{% block reset_complete %}
   <!-- Content -->
    <div id="content" class="colM">

        <h1>Password reset successful</h1>

<!--        <p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>-->
        <p>Your password has been set.  You may go ahead and log in now</p>
        <p><a href="{% url 'login' %}">Login</a></p>
        <br class="clear">
    </div>
    <!-- END Content -->

<!-- END Container -->
{% endblock %}

accounts/templates/reset_password.html
{% extends 'password_base.html' %}
{% block reset %}
  <!-- Content -->
    <div id="content" class="colM">

        <h1>Password reset</h1>


<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">
<!--    <input type="hidden" name="csrfmiddlewaretoken" value="Mlfn99C18YbrHpSFu0T7uwSPl2SsYeWxNAUevVim97u3DCuRDM7wucomeZp5LY9N">-->
    {% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-email">

        <label for="id_email">Email address:</label>
        {{ form.email }}
    </div>
    <input type="submit" value="Reset my password">
</fieldset>
</form>



        <br class="clear">
    </div>
    <!-- END Content -->
{% endblock %}