accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

# app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    # path('change_password/', views.changepasssword, name='change_password'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_complete.html'),
         name='password_reset_complete'),

    # change password
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='change_password.html'),
         name='password_change'),
    path('change_password_done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
         name='password_change_done'),
]

collab_suite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('suiteapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

suiteapp/urls.py
# from dajaxice.core import dajaxice_autodiscover, dajaxice_config
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.conf import settings

from django.urls import path
from. import views

app_name = 'suiteapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('mysite/', views.mysite, name='mysite'),
    path('task/', views.task, name='task'),
    path('repository/', views.repository, name='repository'),
    # path('taskpage/', views.taskpage, name='taskpage'),
    path('taskpage/??/', views.taskpageFunc, name='taskpage'),
    # path('add_site_member/<str:pk>/', views.add_site_member, name='add_site_member'),
    path('add_site_member/teenage-pregnancy/', views.AjaxHandlerView.as_view(), name='add_site_member'),
    path('delete_files/<str:dept>/<str:pk>/', views.deleteFile, name='deletefile'),
    # delete_files/<str:dept>/??/+=/<str:pk>/t4/????piAss??/
    path('delete_folder/<str:pk>/??/+=/<str:dep>/t4/????piAss??<str:name>ug/<str:fk>/', views.deleteFolder, name='delete_folder'),
    path('read/<str:pk>/', views.openfile, name='open_file'),
    path('open_department/<str:pk>/', views.openDepartment, name='open_department'),
    path('open_faculty/<str:pk>/', views.openFaculty, name='open_faculty'),
    path('open_folder/<str:pk>/', views.open_folder, name='open_folder')
]

suiteapp/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


# Create your models here.
class Faculty(models.Model):
    faculty_id = models.AutoField(primary_key=True)
    faculty_name = models.CharField(
        max_length=255,
        unique=True,
        blank=True,
        default='_'
    )

    def __str__(self):
        return str(self.faculty_name)

    class Meta:
        verbose_name_plural = 'Faculties'


class Department(models.Model):
    dept_id = models.AutoField(primary_key=True)
    dept_name = models.CharField(
        max_length=255,
        unique=True,
        blank=True, default='-'
    )
    faculty = models.ForeignKey(Faculty, null=True, verbose_name="faculty", on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.dept_name)


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            username=username,
        )

        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    username = models.CharField(
        verbose_name='username',
        max_length=255,
        unique=True,
    )
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    firstname = models.CharField(
        verbose_name='firstname',
        max_length=255,
        null=True,
    )
    surname = models.CharField(
        verbose_name='lastname',
        max_length=255,
        null=True,
    )
    othername = models.CharField(
        verbose_name='middlename',
        max_length=255,
        null=True,
    )
    gender = models.CharField(
        verbose_name='gender',
        max_length=255,
        null=True, default='null',
    )
    # faculty = models.ForeignKey(
    #     Faculty,
    #     verbose_name='faculty',
    #     null=True, default='null',
    #     on_delete=models.SET_NULL,
    # )
    department = models.ForeignKey(
        Department,
        verbose_name='department',
        null=True,
        on_delete=models.SET_NULL,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username


    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    def get_full_name(self):
        # The user is identified by their email address
        return self.firstname + " " + self.othername + " " + self.surname

    class Meta:
        verbose_name_plural = 'Users'


class Folder(models.Model):
    folder_id = models.AutoField(primary_key=True)
    folder_name = models.CharField(max_length=255)
    created_on = models.DateTimeField(auto_now_add=True)
    is_rep = models.BooleanField(default=True)
    department = models.ForeignKey(Department, blank=True, null=True, on_delete=models.SET_NULL)
    faculty = models.ForeignKey(Faculty, blank=True, null=True, on_delete=models.SET_NULL)
    created_by = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    main_folder = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.folder_name)

    
class File(models.Model):
    uploaded_by = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    file_id = models.AutoField(primary_key=True)
    filepath = models.FileField(upload_to='files/', null=True, verbose_name="")
    uploaded_at = models.DateTimeField(auto_now_add=True)
    department = models.ForeignKey(Department, blank=True, null=True, on_delete=models.SET_NULL,)
    faculty = models.ForeignKey(Faculty, blank=True, null=True, on_delete=models.SET_NULL, )
    is_rep = models.BooleanField(default=False)
    folder = models.ForeignKey(Folder, blank=True, null=True, on_delete=models.CASCADE)
    is_task = models.BooleanField(default=False)

    def __str__(self):
        return str(self.filepath)  # + ":" + str(self.filepath)

    def last_10_files(self):
        return File.objects.order_by('-file_id').all()

    def display_text_file(self):
        with open(self.filepath.path) as fp:
            return fp.read().replace('\n', '<br>')


class Site(models.Model):
    site_name = models.CharField(max_length=200)
    site_id = models.CharField(max_length=200, primary_key=True, unique=True)
    description = models.TextField()
    site_visibilty = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.site_name)


class Task(models.Model):
    task_id = models.AutoField(primary_key=True)
    priority = models.CharField(max_length=7, )
    due_date = models.DateField(null=True)
    due_time = models.TimeField(null=True)
    assignee = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    comment = models.TextField(blank=True)
    # assigner = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    # task_file = models.FileField(upload_to='files/', null=True, verbose_name="",)

    def __str__(self):
        return str(self.comment)


class Taskfile(models.Model):
    task_id = models.AutoField(primary_key=True)
    task_file = models.FileField(upload_to='files/', null=True, verbose_name="")


class Site_Folder(models.Model):
    folder_id = models.AutoField(primary_key=True)
    folder_name = models.CharField(max_length=255, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.folder_name)


class Role(models.Model):
    role = models.CharField(max_length=20)
    
    def __str__(self):
        return str(self.id)


class SiteUser(models.Model):
    site = models.ForeignKey(Site, null=True, on_delete=models.SET_NULL) 
    user = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    role = models.ForeignKey(Role, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.site)

suiteapp/forms.py
from django import forms
from .models import *


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    GEN_CHOICES = [('select', ''),
                   ('male', 'Male'),
                   ('female', 'Female'),
                   ('other', 'Other')]
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                    'placeholder': 'enter password'}))
    password2 = forms.CharField(label='Password confirmation',
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 're-enter password'}))
    # department = forms.ModelChoiceField(queryset=Department.objects.all(),
    #                                     widget=forms.Select(attrs={'class': 'form-control'}))
    # faculty = forms.ModelChoiceField(queryset=Faculty.objects.all(),
    #                                  widget=forms.Select(attrs={'class': 'form-control'}))
    gender = forms.ChoiceField(choices=GEN_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'email'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'username'}))
    othername = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                              'placeholder': 'othernames'}))
    surname = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter your surname'}))
    firstname = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter firstname'}))

    # faculty = forms.SelectMultiple(attrs={'required': "required"})

    class Meta:
        model = MyUser
        fields = ('firstname', 'email', 'username', 'department', 'password1',
                  'password2', 'gender', 'surname', 'othername')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ["filepath", "uploaded_by", 'department', 'faculty', 'is_rep', 'folder', 'is_task']


CHOICES = [('private', 'Private'),
           ('medium', 'Medium'),
           ('public', 'Public')]


class SiteForm(forms.ModelForm):
    site_visibility = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(attrs={'class': 'form-ckeck'}))
    site_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter the name of the site...', 'class': 'form-control'}))
    site_id = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'site id...', 'class': 'form-control'}))

    # description = forms.CharField(widget=forms.TextInput(attrs={'':'form-control'}))

    class Meta:
        model = Site
        fields = ["site_name", "site_id", "description", 'site_visibility']


class FolderForm(forms.ModelForm):
    folder_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter the folder name...'}))

    class Meta:
        model = Folder
        fields = ['folder_name', 'is_rep', 'faculty', 'department', 'created_by', 'main_folder']


class SiteUserForm(forms.ModelForm):
    class Meta:
        model = SiteUser
        fields = ['site', 'user', 'role']


class DateInput(forms.DateInput):
    input_type = 'date'

    def clean_date(self):
        cleaned_data = self.cleaned_data
        due_date = cleaned_data.get("due_date")
        return due_date


class TimeInput(forms.TimeInput):
    input_type = 'time'

    def clean_time(self):
        cleaned_data = self.cleaned_data
        due_time = cleaned_data.get("due_time")
        return due_time


class TimeForm(forms.Form):
    time_field = forms.TimeField(widget=TimeInput())


class TaskForm(forms.ModelForm):
    PRIO_CHOICES = [('high', 'Hgh'),
                    ('medium', 'Medium'),
                    ('low', 'Low')]
    # task_file =  forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    priority = forms.ChoiceField(choices=PRIO_CHOICES, widget=forms.Select(attrs={'class': 'form-control col-sm-2'}))
    due_date = forms.DateField(widget=DateInput(attrs={'class': 'form-control col-sm-2'}))
    due_time = forms.TimeField(widget=TimeInput(attrs={'class': 'form-control col-sm-2'}))
    comment = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control col-sm-4', 'rows': 7, }))

    class Meta:
        model = Task
        fields = ['priority', 'due_date', 'due_time', 'assignee', 'comment', ]


class TaskFileForm(forms.ModelForm):
    filepath = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True, 'class': 'form-control col-sm-4'}))

    class Meta:
        model = File
        fields = ['is_task', 'filepath', 'uploaded_by']
# select for dropdown
# choice for radio button

suiteapp/templates/controls/assignmodal.html
<!--Assignees modal -->
<div class="container">
    <!-- The Modal -->
    <div class="modal row" id="assignModal">
      <div class="assign-modal-dialog col-sm-6">
        <div class="assign-modal-content">

          <!-- Modal Header -->
          <div class="modal-header">
            <button class="btn btn-primary" type="submit">Add</button>
            <button class="btn btn-primary" type="button" onclick="document.getElementById('assignModal').style.display='none'">&times;</button>
          </div>

          <!-- Modal body -->
          <div class="assign-modal-body" style="height:400px;">
            <div class="row" style="height:100%;">
              <!-- Leftdiv card -->
              <div class="card leftdiv col-sm-5">
                 <div class="" style="background: #88888829;height:15%;position:static;width:100%;margin-left:0px;">
                    <form class="form-inline my-2 my-lg-0" style="padding-top:1%;width:100%;" >
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                      </form>
                 </div>
                 <hr />
                 <div class="card-body">

                 </div>
              </div>

              <!-- Rightdiv card-->
              <div class="card rightdiv col-sm-5">
                <label>Select a file to upload...</label>
                <input type="file" name="fileUpload" onchange="setFileName(event.target.files[0].name)" />
              </div>
            </div>
          </div>


          <!-- Modal footer -->
          <div class="modal-footer">
          </div>

        </div>
      </div>
    </div>

  </div>

suiteapp/templates/controls/createfoldermodal.html
<!-- Create folder Modal -->
<style>
  #id_folder_name{
    width: 100%;
  }

</style>
<div class="modal fade" id="folderModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Enter the name of the folder</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST">
          {% csrf_token %}
            <div class="">
                {{ create_folder.folder_name }}
                {{ create_folder.is_rep }}
                {{ create_folder.created_by }}
                {{ create_folder.faculty }}
                {{ create_folder.department }}
                {{ create_folder.main_folder }}
            </div>
<!--            <p id="dep">{{ request.path|slice:"17:19" }}</p>-->
            
             <!-- Modal footer -->
            <div class="modal-footer">
              <button class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="submit" class="btn btn-primary">Create folder</button>
            </div>
        </form>
      </div>
    </div>
  </div>

suiteapp/templates/controls/navbar.html
{% url 'suiteapp:index' as index %}
{% url 'suiteapp:task' as task %}
{% url 'suiteapp:mysite' as mysite %}
{% url 'suiteapp:repository' as repository %}
{% url 'suiteapp:taskpage' as taskpage %}
<style> .active {background-color:white;} </style>
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <h5><span class="navbar-toggler-icon" style="height:30px;"><h5 style="margin-left: 50px;">Menu</h5></span></h5>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item {% if request.path == index %} active {% endif %}">
              <a class="nav-link text-primary" href="{% url 'suiteapp:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-primary" href="" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Site
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item fa fa-globe" href="" data-toggle="modal" data-target="#sitemodal"><r>Create site</r></a>
                  <a class="dropdown-item fa fa-folder" href="{% url 'suiteapp:repository' %}"><r>Repository</r></a>
                  <a class="dropdown-item" href="{% url 'suiteapp:mysite' %}">My Site</a>
                  <div class="dropdown-divider"></div>
                    <a class="dropdown-item fa fa-tasks" href="{% url 'suiteapp:task' %}"><r>My Task</r></a>
                </div>
            </li>
            <li class="nav-item {% if request.path == task %} active {% endif %}">
              <a class="nav-link text-primary" href="{% url 'suiteapp:task' %}">Tasks</a>
            </li>
            <li class="nav-item {% if request.path == repository %} active {% endif %}">
              <a class="nav-link text-primary" href="{% url 'suiteapp:repository' %}">Repository</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-primary" href="{% url 'password_change' %}">Change Password</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle fa fa-user text-primary" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item fa fa-globe" href="{% url 'password_change' %}"><r>Change Password</r></a>
                <a class="dropdown-item fa fa-user" href="#"><r>Profile</r></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item fa fa-sign-out" href="{% url 'logout' %}" onclick="sessionStorage.clear()"><r>Logout</r></a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

suiteapp/templates/controls/sitemodal.html
<script>
  $(document).ready(function(){
      $("#id_site_name").keyup(function(){
      $('#id_site_id')[0].value=$('#id_site_name').val().toLowerCase();

      // Replace whitepsaces with "-"
      var replaceSpace = $(this).val();
      var result = replaceSpace.replace(/ /g, "-");
      document.getElementById("id_site_id").value = result;
  });
  });
  </script>
<style>
   #id_site_id { text-transform: lowercase; }
</style>
  <!-- Modal -->
   <div class="modal fade sitemodal align-items-center" id="sitemodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">

        <div class="modal-body">
          <form class="modal-content animate" action="" method="post" style="max-width: 340px;">
            {% csrf_token %}
          <div class="container" style="padding-top: 5%; padding-left:8%; padding-right: 8%;background-color:white;">

              <label for="id_site_name"><b>Site Name/Title</b></label>
                {{ siteform.site_name }}
                <br />
              <label for="id_site_id"><b>Site_id</b></label> <br />
                {{ siteform.site_id }}
              <label for="id_description"><b>Description</b></label>
                {{ siteform.description }}
              <label for="id_site_visibility"><b>Visibility</b></label>
                {{ siteform.site_visibility }}
            <button type="submit" class="btn btn-primary">Create site</button>
            <button type="button" class="btn btn-danger" onclick="document.getElementById('sitemodal').style.display='none'" data-dismiss="modal">Cancel</button>
      </div>
      </form>
        </div>
      </div>
    </div>
  </div>

suiteapp/templates/controls/uploadmodal.html
{% load static %}
<!--File upload modal-->
<div class="container">
  <!-- The Modal -->
  <div class="modal uploadmodal" id="myModal">
    <div class="modal-dialog">

        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
      <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">File upload</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <div class="row">
            <div class="col-1">
                <img id="aud" src="{% static 'images/fileicons/audioicon.jpeg' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="def" src="{% static 'images/fileicons/deficon.png' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="docs" src="{% static 'images/fileicons/docs.png' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="html" src="{% static 'images/fileicons/htmlicon.png' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="img" src="{% static 'images/fileicons/imageicon.png' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="pdf" src="{% static 'images/fileicons/pdficon.png' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="pow" src="{% static 'images/fileicons/powicon.jpeg' %}" height="50" width="50" alt="icon" style="display:none;">
            </div>
            <div class="col" style="padding-top: 13px;">
                <h6 id="file" name="file"></h6>
            </div>
          </div>
          <div style="text-align: center; border: 1px dashed rgb(9, 216, 147);">
            <label for="id_filepath">Click to select a file to upload...</label>
              {{ form.filepath }}
              {{ form.uploaded_by }}
              {{ form.department }}
              {{ form.faculty }}
              {{ form.is_rep }}
              {{ form.folder }}
              <script type="text/javascript">
              </script>
          </div>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary" style="width:100%;color:white;">
            <i class="fas fa-upload" style="color: white;"></i>Upload</button>
        </div>

      </div>
        </form>
    </div>
  </div>

</div>
<script type="text/javascript">
document.getElementById('id_filepath').addEventListener("change", function(){setFileName(event.target.files[0].name)});

  // document.getElementById('id_department').style.display='none';
  // document.getElementById('id_is_rep').style.display='none';
  // function upFunction(){
  //   document.getElementById('id_department').value =  sessionStorage.getItem('dept_id')
  //   document.getElementById('id_faculty').value =  sessionStorage.getItem('faculty')
  // }
</script>